### ISSUE TITLE
[DOCS] RAG Chatbot app page should link to RAG Chatbot tutorial page

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-doc#1048]
### Issue Description

This [page](https://docs.taipy.io/en/develop/gallery/llm/8_rag_chatbot/) should link to this [page](https://docs.taipy.io/en/develop/tutorials/fundamentals/5_rag_chatbot/)

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/55eb9af9-b53a-4d3d-a7ef-5c922a2e8a7b)

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by jrobinAV** [comment]
@Satoshi-Sh I just assigned you the issue. Thank you.

This issue is quite small and self-explanatory, so there is no pb for you to work on it. But just for information, we usually prefer our maintainer's team to first review an issue before assigning it to a contributor. That's to ensure the description is detailed enough, correct, and consistent with the others. The issues already reviewed are categorized as a "good first" or "help wanted". 

Thank you anyway for your help on this issue (and the others 😉 ).
