### ISSUE TITLE
BUG-Notebook link is dead GUI tutorial

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-doc#697]
On this page:
https://docs.taipy.io/en/latest/knowledge_base/tutorials/understanding_gui/#using-notebooks

This link is dead:
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/a4528f61-7e32-41d3-afae-74c2b25e9521)

**Comment by FabienLelaquais** [comment]
This was discussed with @FlorianJacta yesterday.
This problem is due to the migration of the legacy Getting Started into the Knowledge Base structure that forgot about regenerating the notebook document.
I recommend that this generation is performed manually, once, and that the resulting file be stored in the doc repository itself, where it belongs. When the code is updated in the future, so should the notebook.
The generation script, if generic enough, could be stored in the `tools` directory for the doc for future use.

**Comment by FabienLelaquais** [comment]
So I manually created that notebook file, so a minimum of visitors would be impacted.
To me this will be closed at the end of the sprint, unless anyone complains.

Note that this was merged in develop and 3.0 as part of far larger PRs.
