### ISSUE TITLE
Add taipy-cloud deployment doc

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy-doc#816]
Deploying an application on taipy-cloud must be documented.
We already have content and videos that can be added to the current documentation.

**Comment by jrobinAV** [comment]
There is also a tip in the knowledge base documentation that the documentation can reference. Or the opposite.
@FlorianJacta Should know.

**Comment by FlorianJacta** [comment]
We could just make [this](https://docs.taipy.io/en/latest/knowledge_base/tips/taipy_cloud_deploy/) the doc

**Comment by FlorianJacta** [comment]
Answer to my comment

The tips are not up to date, the machine is 'tiny'. It would need to be a bit more detailed. And there should be a section added about connecting to the cloud machine with SSH or Filezilla. Also, it should be mentioned that there is a directory /home/user/data where you can drop all the data you want because we don't touch it between deployments. In particular, if you have .csv or model files, you should copy them into this folder to use them in your app and not have a 200MB zip file

**Comment by florian-vuillemot** [comment]
Please also mention that the application runs on Linux and not on Windows. Some users have added Windows-specific libraries that failed during installation.
